### ISSUE TITLE
avoid reading timeblocks

### ISSUE THREAD

**Issue by KrisThielemans** [ETSIhackers/geom_visualisation#11]
@naegelejd found a clean work-around to avoid reading all the time-blocks, see https://github.com/ETSInitiative/PETSIRD/pull/58/commits/37bea0f68db4fd3409531dc3b437870215968fdf and
https://github.com/ETSInitiative/PETSIRD/pull/58#issuecomment-2460440885

**Comment by MaxTousss** [comment]
Closed since PR13 dealt with this.
